// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WebAppPhotoSiteImages.Database;

namespace WebAppPhotoSiteImages.Migrations
{
    [DbContext(typeof(DbMgmt))]
    [Migration("20180521191426_add_UserId_to_entities")]
    partial class add_UserId_to_entities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Common.ImageCommentMsg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comment");

                    b.Property<DateTime>("DateCreated");

                    b.Property<Guid>("ImagePostMsgId");

                    b.Property<int>("Rate");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ImagePostMsgId");

                    b.ToTable("ImageCommentMsgs");
                });

            modelBuilder.Entity("Common.ImagePostMsg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AverageRate");

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Description");

                    b.Property<string>("HashTag");

                    b.Property<byte[]>("Image");

                    b.Property<string>("ImageTitle");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("ImagePostMsgs");
                });

            modelBuilder.Entity("Common.TextMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.ToTable("TextMessages");
                });

            modelBuilder.Entity("Common.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Common.ImageCommentMsg", b =>
                {
                    b.HasOne("Common.ImagePostMsg", "ImagePostMsg")
                        .WithMany()
                        .HasForeignKey("ImagePostMsgId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
